Add tabs component
openSUSE/obs-patterns pull request #11
Opened 2018-08-06 16:42 UTC by dmarcoux

2018-08-06 16:42 UTC, hennevogel commented
Deploy preview for *obs-patterns* ready!

Built with commit 66eb83297de53528dbe3ab5c9b869c1392a24e7d

https://deploy-preview-11--obs-patterns.netlify.com

2018-08-07 10:18 UTC, mdeniz requested changes

2018-08-07 10:18 UTC, mdeniz commented on _posts/components/2018-08-06-tabs.html
> +             Javascript code in OBS makes the tabs responsive
The indentation is lost when shown. And you need a period at the end of the sentence.

2018-08-07 10:18 UTC, mdeniz commented on _posts/components/2018-08-06-tabs.html
> +description: The tabs need a container (which is a %div in the example).
Please use bold for **%div** all the other **%whatever** syntax :smile:

2018-08-07 10:18 UTC, mdeniz commented on _posts/components/2018-08-06-tabs.html
> +             Due to a Jekyll limitation, the Ruby code in the 'class' attribute of %a has extra double quotes(") in the example (so remove them when copying)
I guess we need to do a different thing for this repo, we need to have code for examples that is shown as a result, and the example highlighted. In many cases will be a duplication but in some others we need to have those separated because they are slightly different.

2018-08-07 10:53 UTC, dmarcoux commented on _posts/components/2018-08-06-tabs.html
> +             Due to a Jekyll limitation, the Ruby code in the 'class' attribute of %a has extra double quotes(") in the example (so remove them when copying)
I would like to avoid the duplication if possible. I will look if it's possible.

2018-08-07 15:01 UTC, dmarcoux commented
I found a way to have Ruby methods in our examples. It involves monkey patching `Object`. This is done in a plugin. Let me know what you think.

2018-08-07 15:05 UTC, mdeniz approved these changes

2018-08-07 15:06 UTC, mdeniz commented
I think we still need another layout to not use the same code for the example than the snippet shown, sometime you want to have more than one example of the same thing and you don't want to repeat the snippet :+1:

2018-08-07 15:07 UTC, merged