Add modal for confirmations instead of data-confirm boxes
openSUSE/obs-patterns pull request #19
Opened 2018-09-13 08:42 UTC by mdeniz

Add a component for showing a small centered modal usefull for
confirmations of destructive actions such as a deletion

It will show something like this:

![image](https://user-images.githubusercontent.com/11314634/45412442-e63db500-b676-11e8-907e-ddd06ce6cf86.png)

instead of:

![image](https://user-images.githubusercontent.com/11314634/45412560-37e63f80-b677-11e8-8f40-2ca0fd1bbd82.png)

2018-09-13 08:43 UTC, hennevogel commented
Deploy preview for *obs-patterns* ready!

Built with commit f0546d6e1cb4de3d5d4ffd719d7da72d4936ac0b

https://deploy-preview-19--obs-patterns.netlify.com

2018-09-13 09:21 UTC, dmarcoux requested changes
The screenshot in the PR's description is the old modal (before we changed the buttons). It can be removed, the preview is enough.

2018-09-13 09:21 UTC, dmarcoux commented on _posts/components/2018-09-12-modal_confirm.html
> +                    Do you really want to delete a thing?
I would do the same as what we did in the PR: `Delete thing?`

2018-09-13 09:21 UTC, dmarcoux commented on _posts/components/2018-09-12-modal_confirm.html
> +                %p Please confirm that you want to delete a thing
`Please confirm that you want to delete thing #1234`

2018-09-13 09:21 UTC, dmarcoux commented on _posts/components/2018-09-12-modal_confirm.html
> +                //= form_tag(some_path(thing), method: :post) do
We could include the helpers by adding them in [here](https://github.com/openSUSE/obs-patterns/blob/1afdc83db923df1f792e067aba4587c2b9b60533/_plugins/ruby.rb). It would make the example clearer and it can be copy/pasted easily. It's a way to go around them not being defined in this project.

2018-09-18 11:55 UTC, mdeniz commented on _posts/components/2018-09-12-modal_confirm.html
> +                //= form_tag(some_path(thing), method: :post) do
`form_tag` is in Rails and is a little bit complex to put the code there...

I hope that this pattern library is not for C&P the code... is to know how it has to be constructed. Either you do it with helpers or by hand in html...

2018-09-18 11:56 UTC, mdeniz commented on _posts/components/2018-09-12-modal_confirm.html
> +                %p Please confirm that you want to delete a thing
The text is not the main thing here, up to the developer that is going to use this

2018-09-18 11:56 UTC, mdeniz commented on _posts/components/2018-09-12-modal_confirm.html
> +                    Do you really want to delete a thing?
The text is not the main thing here, up to the developer that is going to use this

2018-09-18 11:56 UTC, mdeniz commented
Screenshot changed @dmarcoux please review

2018-09-18 13:38 UTC, dmarcoux approved these changes

2018-09-18 13:39 UTC, Ana06 approved these changes
LGTM :bouquet:

2018-09-18 13:39 UTC, Ana06 commented on _posts/components/2018-09-12-modal_confirm.html
> +                    Do you really want to delete a thing?
It doesn't hurt that the text is coherent :wink:

2018-09-18 13:40 UTC, dmarcoux commented on _posts/components/2018-09-12-modal_confirm.html
> +                //= form_tag(some_path(thing), method: :post) do
I do copy/paste some of the patterns sometimes, but it's true that we don't literally copy/paste everything. It's fine.

2018-09-18 13:40 UTC, merged