Add collapse molecule
openSUSE/obs-patterns pull request #40
Opened 2018-11-26 12:13 UTC by dmarcoux

2018-11-26 12:14 UTC, hennevogel commented
Deploy preview for *obs-patterns* ready!

Built with commit 7220af23f0ccc7b08bb9ad39ceafa2bd81184d18

https://deploy-preview-40--obs-patterns.netlify.com

2018-11-26 12:56 UTC, Ana06 requested changes
I would add more details more in the commit description (why is that needed?)

2018-11-26 12:56 UTC, Ana06 commented on _posts/molecules/2018-11-26-collapse.html
> +%a.request{ href: "/request/show/1" }
`request{ href: "/request/show/1" }` is not really related to collapse, so I would remove it to remove complexity (same everywhere)

2018-11-26 12:56 UTC, Ana06 commented on _posts/molecules/2018-11-26-collapse.html
> +  %span.badge.state-obsolete package1
same here you can just write element1 (same everywhere)

2018-11-26 12:56 UTC, Ana06 commented on _posts/molecules/2018-11-26-collapse.html
> +  %i.fas.fa-chevron-up.collapser.text-secondary.ml-1.mr-1
I would put also something more generic here. For example: 

```
%span.collapser See less elements
%span.expander See more elements
```

2018-11-26 13:02 UTC, dmarcoux commented
Somehow, it's not working (both icons are displayed)

2018-11-26 13:37 UTC, Ana06 commented
@dmarcoux 

> Somehow, it's not working (both icons are displayed)

haven't you forgotten the css? :thinking:

2018-11-26 14:19 UTC, dmarcoux commented
The CSS from OBS is included [here](https://github.com/openSUSE/obs-patterns/blob/6564f5a6e590c1b5a7648fcf315cd5f03c2f0818/_includes/head.html#L10). I think there's an issue with CORS.

2018-11-27 09:36 UTC, dmarcoux commented
I realized what the issue is. The CSS and JS needed for this to work is in the staging-workflow branch.

2018-11-27 10:34 UTC, Ana06 commented
@dmarcoux 

> I realized what the issue is. The CSS and JS needed for this to work is in the staging-workflow branch.

That is what I meant, you could add it manually, right?

2018-11-27 10:35 UTC, Ana06 reviewed
Apart from the missing css, LGTM

2018-11-27 10:36 UTC, dmarcoux commented
I think I will just wait for the staging-workflow branch to be merged on master. I sent this PR to be sure to not forget about adding the collapse molecule.

2018-11-27 20:32 UTC, bgeuken approved these changes

2018-12-19 12:47 UTC, dmarcoux commented
@openSUSE/obs-frontend Please have a look.

The staging workflow branch has been merged in OBS, this now works. I also pushed some changes to display the collapsed/expanded version of the collapse molecule.

2018-12-19 13:27 UTC, Ana06 approved these changes

2018-12-19 13:30 UTC, Ana06 requested changes
I didn't want to approve it :see_no_evil: It seems something is wrong with the Javascript. It crasses when clicking `See less elements`

2018-12-19 14:42 UTC, dmarcoux commented
I don't know why because it works in OBS, but not in this project...

2019-01-16 14:58 UTC, closed without merging