Update breadcrumb molecule
openSUSE/obs-patterns pull request #49
Opened 2018-12-14 14:20 UTC by bgeuken

* Add 'home' icon. All OBS breadcrumbs start with it.
* Adjust to recent changes (dropping the 'OBS label') made in
  https://github.com/openSUSE/open-build-service/pull/6592

2018-12-14 14:21 UTC, hennevogel commented
Deploy preview for *obs-patterns* failed.

Built with commit aa34021125578fdb372bc0eba0cc45f4c4cbd31b

https://app.netlify.com/sites/obs-patterns/deploys/5c13bc43db7e70000b4a570a

2018-12-14 14:47 UTC, dmarcoux requested changes

2018-12-14 14:47 UTC, dmarcoux commented on _posts/molecules/2018-1-2-breadcrumbs.html
> +      = link_to('#', title: 'Open Build Service') do
This doesn't work since it's Rails helper. You can leave it here, but as a comment and then add the `%a`.

2018-12-17 11:22 UTC, bgeuken commented
@dmarcoux updated

2018-12-17 12:15 UTC, dmarcoux approved these changes
I don't know why, but we used the old hash syntax in our example. Anyway, I don't want to block this only for that.

2018-12-17 15:55 UTC, merged