Update autocomplete pattern
openSUSE/obs-patterns pull request #51
Opened 2019-01-13 10:05 UTC by bgeuken

Adopts our pattern library to recent changes made in PR 6671.

https://github.com/openSUSE/open-build-service/pull/6671

2019-01-13 10:05 UTC, hennevogel commented
Deploy preview for *obs-patterns* ready!

Built with commit cb7f68b327f48d8aea76a6edd2d5e80330008aa9

https://deploy-preview-51--obs-patterns.netlify.com

2019-01-14 10:31 UTC, dmarcoux requested changes

2019-01-14 10:31 UTC, dmarcoux commented on _posts/molecules/2018-10-01-autocomplete.html
> +             OBS provides an autocomplete parti, including javascript for handling the autocomplete request and spinner. For
autocomplete parti? What is a parti?

2019-01-14 10:31 UTC, dmarcoux commented on _posts/molecules/2018-10-01-autocomplete.html
> +             OBS provides an autocomplete parti, including javascript for handling the autocomplete request and spinner. For
We should capitalize `Javascript`.

2019-01-14 10:31 UTC, dmarcoux commented on _posts/molecules/2018-10-01-autocomplete.html
> +             further customization of autocomplete events please refer to the jquery autocomplete documentation (https://jqueryui.com/autocomplete/).
It should be `jQuery` and the link should be `[jQuery autocomplete documentation](https://jqueryui.com/autocomplete/)`

2019-01-14 10:31 UTC, dmarcoux commented on _posts/molecules/2018-10-01-autocomplete.html
> +    %input.form-control#input-id{ class: 'obs-autocomplete form-control', data: { source: '/path/to/autocomplete/data' },
The classes should be added directly (so not inside `{}`). `form-control` is also added twice.

2019-01-14 16:47 UTC, bgeuken commented on _posts/molecules/2018-10-01-autocomplete.html
> +             OBS provides an autocomplete parti, including javascript for handling the autocomplete request and spinner. For
Actually it's `JavaScript`

2019-01-14 16:53 UTC, dmarcoux commented on _posts/molecules/2018-10-01-autocomplete.html
> +             further customization of autocomplete events please refer to the [jQuery autocomplete documentation](https://jqueryui.com/autocomplete/).
```suggestion
             further customization of autocomplete events, please refer to the [jQuery autocomplete documentation](https://jqueryui.com/autocomplete/).
```

2019-01-14 16:53 UTC, dmarcoux commented on _posts/molecules/2018-10-01-autocomplete.html
> +    %input.form-control.obs-autocomplete.form-control#input-id{ data: { source: '/path/to/autocomplete/data' },
```suggestion
    %input.obs-autocomplete.form-control#input-id{ data: { source: '/path/to/autocomplete/data' },
```

2019-01-14 16:54 UTC, dmarcoux commented on _posts/molecules/2018-10-01-autocomplete.html
> +    %input.form-control#input-id{ class: 'obs-autocomplete form-control', data: { source: '/path/to/autocomplete/data' },
Still valid, I added a suggestion.

2019-01-15 09:35 UTC, bgeuken commented
@dmarcoux updated

2019-01-15 09:49 UTC, dmarcoux commented
I added some suggestions yesterday. Please have a look. After that, it's all good.

2019-01-16 12:13 UTC, bgeuken commented
@dmarcoux Overlooked them before. Please have another look

2019-01-16 12:24 UTC, dmarcoux approved these changes

2019-01-16 12:25 UTC, merged