Document the collapsible text pattern
openSUSE/obs-patterns pull request #57
Opened 2019-02-18 09:22 UTC by bgeuken

We use this pattern when we don't want to show the full text by default.
In that case we only show a subset of it and hide the rest. The full
text can be toggled via a 'Show more' link.

2019-02-18 09:22 UTC, hennevogel commented
Deploy preview for *obs-patterns* failed.

Built with commit 911799a9099be684d28c533fad595cf4729793bb

https://app.netlify.com/sites/obs-patterns/deploys/5c6a795b8710ca000baa149f

2019-02-18 09:23 UTC, bgeuken commented
This depends on the CSS and JS of https://github.com/openSUSE/open-build-service/pull/6993

2019-02-18 11:15 UTC, dmarcoux requested changes

2019-02-18 11:15 UTC, dmarcoux commented on _posts/molecules/2019-02-18-collapsible_text.html
> +      = simple_format(text, class: 'm-0 p-0')
`simple_format` is not working in Jekyll. It can be a comment like what we have with the `render partial` above.

2019-02-22 11:05 UTC, bgeuken commented
@dmarcoux Updated. Please have another look

2019-02-22 12:32 UTC, dmarcoux approved these changes

2019-02-22 12:32 UTC, merged